/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JukeboxRouteImport } from './routes/jukebox'
import { Route as KaraokeRouteImport } from './routes/karaoke'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as PgRouteImport } from './routes/pg'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RepertorioRouteImport } from './routes/repertorio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SomRouteImport } from './routes/som'
import { Route as TvRouteImport } from './routes/tv'
import { Route as RegiaoIndexRouteImport } from './routes/regiao.index'
import { Route as RegiaoCidadeRouteImport } from './routes/regiao.$cidade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JukeboxRoute = JukeboxRouteImport.update({
  id: '/jukebox',
  path: '/jukebox',
  getParentRoute: () => rootRouteImport,
} as any)
const KaraokeRoute = KaraokeRouteImport.update({
  id: '/karaoke',
  path: '/karaoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const PgRoute = PgRouteImport.update({
  id: '/pg',
  path: '/pg',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertorioRoute = RepertorioRouteImport.update({
  id: '/repertorio',
  path: '/repertorio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SomRoute = SomRouteImport.update({
  id: '/som',
  path: '/som',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const RegiaoIndexRoute = RegiaoIndexRouteImport.update({
  id: '/regiao/',
  path: '/regiao/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegiaoCidadeRoute = RegiaoCidadeRouteImport.update({
  id: '/regiao/$cidade',
  path: '/regiao/$cidade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jukebox': typeof JukeboxRoute
  '/karaoke': typeof KaraokeRoute
  '/obrigado': typeof ObrigadoRoute
  '/pg': typeof PgRoute
  '/privacidade': typeof PrivacidadeRoute
  '/repertorio': typeof RepertorioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/som': typeof SomRoute
  '/tv': typeof TvRoute
  '/regiao/$cidade': typeof RegiaoCidadeRoute
  '/regiao/': typeof RegiaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jukebox': typeof JukeboxRoute
  '/karaoke': typeof KaraokeRoute
  '/obrigado': typeof ObrigadoRoute
  '/pg': typeof PgRoute
  '/privacidade': typeof PrivacidadeRoute
  '/repertorio': typeof RepertorioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/som': typeof SomRoute
  '/tv': typeof TvRoute
  '/regiao/$cidade': typeof RegiaoCidadeRoute
  '/regiao': typeof RegiaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jukebox': typeof JukeboxRoute
  '/karaoke': typeof KaraokeRoute
  '/obrigado': typeof ObrigadoRoute
  '/pg': typeof PgRoute
  '/privacidade': typeof PrivacidadeRoute
  '/repertorio': typeof RepertorioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/som': typeof SomRoute
  '/tv': typeof TvRoute
  '/regiao/$cidade': typeof RegiaoCidadeRoute
  '/regiao/': typeof RegiaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jukebox'
    | '/karaoke'
    | '/obrigado'
    | '/pg'
    | '/privacidade'
    | '/repertorio'
    | '/sitemap.xml'
    | '/som'
    | '/tv'
    | '/regiao/$cidade'
    | '/regiao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jukebox'
    | '/karaoke'
    | '/obrigado'
    | '/pg'
    | '/privacidade'
    | '/repertorio'
    | '/sitemap.xml'
    | '/som'
    | '/tv'
    | '/regiao/$cidade'
    | '/regiao'
  id:
    | '__root__'
    | '/'
    | '/jukebox'
    | '/karaoke'
    | '/obrigado'
    | '/pg'
    | '/privacidade'
    | '/repertorio'
    | '/sitemap.xml'
    | '/som'
    | '/tv'
    | '/regiao/$cidade'
    | '/regiao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JukeboxRoute: typeof JukeboxRoute
  KaraokeRoute: typeof KaraokeRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PgRoute: typeof PgRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RepertorioRoute: typeof RepertorioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SomRoute: typeof SomRoute
  TvRoute: typeof TvRoute
  RegiaoCidadeRoute: typeof RegiaoCidadeRoute
  RegiaoIndexRoute: typeof RegiaoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jukebox': {
      id: '/jukebox'
      path: '/jukebox'
      fullPath: '/jukebox'
      preLoaderRoute: typeof JukeboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karaoke': {
      id: '/karaoke'
      path: '/karaoke'
      fullPath: '/karaoke'
      preLoaderRoute: typeof KaraokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pg': {
      id: '/pg'
      path: '/pg'
      fullPath: '/pg'
      preLoaderRoute: typeof PgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertorio': {
      id: '/repertorio'
      path: '/repertorio'
      fullPath: '/repertorio'
      preLoaderRoute: typeof RepertorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/som': {
      id: '/som'
      path: '/som'
      fullPath: '/som'
      preLoaderRoute: typeof SomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regiao/': {
      id: '/regiao/'
      path: '/regiao'
      fullPath: '/regiao/'
      preLoaderRoute: typeof RegiaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regiao/$cidade': {
      id: '/regiao/$cidade'
      path: '/regiao/$cidade'
      fullPath: '/regiao/$cidade'
      preLoaderRoute: typeof RegiaoCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JukeboxRoute: JukeboxRoute,
  KaraokeRoute: KaraokeRoute,
  ObrigadoRoute: ObrigadoRoute,
  PgRoute: PgRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RepertorioRoute: RepertorioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SomRoute: SomRoute,
  TvRoute: TvRoute,
  RegiaoCidadeRoute: RegiaoCidadeRoute,
  RegiaoIndexRoute: RegiaoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
